version: 0.0
os: linux
files:
  - source: /
    destination: /opt/codedeploy-agent/deployment-root/7a99d5e3-5b94-4a82-81dc-95e570fb937d/d-709YAG9M8/deployment-archive
#   - source: server_configs/nginx/backend.conf
#     destination: /etc/nginx/sites-enabled/
#     runas: ubuntu
#   - source: server_configs/nginx/backend.conf
#     destination: /etc/nginx/sites-available/
#     runas: ubuntu
#   - source: server_configs/supervisor/backend_supervisor.conf
#     destination: /etc/supervisor/conf.d
#     runas: ubuntu
hooks:
  BeforeInstall:
      - location: /opt/codedeploy-agent/deployment-root/7a99d5e3-5b94-4a82-81dc-95e570fb937d/d-709YAG9M8/deployment-archive/before_install.sh
  AfterInstall:
      - location: /opt/codedeploy-agent/deployment-root/7a99d5e3-5b94-4a82-81dc-95e570fb937d/d-709YAG9M8/deployment-archive/after_install.sh
