version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/project

hooks:
    ApplicationStop:
         - location: scripts/stop_application.sh
            timeout: 300
            runas: ubuntu
            
    BeforeInstall:
        - location: beforeinstall.sh
            timeout: 300
            runas: ubuntu

    AfterInstall:
         - location: afterinstall.sh
            timeout: 300
            runas: ubuntu
         
         - location:  /etc/systemd/system/gunicorn.socket
            timeout: 300
            runas: ubuntu
            
         - location: /etc/systemd/system/gunicorn.socket
            timeout: 300
            runas: ubuntu
            
         - location: /scripts/command
            timeout: 300
            runas: ubuntu
            
         - location: /etc/nginx/sites-available/myproject
            timeout: 300
            runas: ubuntu
            
    ApplicationStart:
         - location: scripts/start_server
            timeout: 300
            runas: ubuntu
            
    
            
   
