version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/project

hooks:
    BeforeInstall:
        - location: beforeinstall.sh
            timeout: 100
            runas: ubuntu

    AfterInstall:
         - location: afterinstall.sh
            timeout: 100
            runas: ubuntu

    
